version: '3.6'
# Requires Docker v18.02 or higher.

################################################################
#   The DockerPHP Project                                      #
#   https://github.com/phpexpertsinc/docker-php                #
#   License: MIT                                               #
#                                                              #
#   Copyright © 2020 PHP Experts, Inc. <sales@phpexperts.pro>  #
#       Author: Theodore R. Smith <theodore@phpexperts.pro>    #
#      PGP Sig: 4BF826131C3487ACD28F2AD8EB24A91DD6125690       #
################################################################

services:
  web:
    image: phpexperts/web:nginx-php7.4
    volumes:
      - .:/var/www
      - ./docker/web:/etc/nginx/custom
      - /etc/group:/etc/group

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

